version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(actions)"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directory: "/"
    commit-message:
      prefix: "deps(go)"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "deps(container)"
    schedule:
      interval: "monthly"
