version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupl
    - err113
    - errorlint
    - exhaustive
    - funlen
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/pulumi/pulumi/sdk/v3/go
            - github.com/go-playground/validator/v10
            - github.com/stretchr/testify/assert
            - dario.cat/mergo
    funlen:
      lines: 100
      statements: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gosec
          - noctx
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
